#Pixel to monitor for any configured target color.
[Pixel Coordinate]
type=coordinate
x=
y=

#First color that can trigger the action cycle.
[Target Color One]
type=color
color=0xFFFFFF

#Second color that can trigger the action cycle.
[Target Color Two]
type=color
color=0xFFFFFF

#First click area in the location cycle.
[Action Location One]
type=coordinate
xmin=
xmax=
ymin=
ymax=

#Second click area in the location cycle.
[Action Location Two]
type=coordinate
xmin=
xmax=
ymin=
ymax=

#Randomized delay after a target color is detected and before the click.
[Sleep Timer]
min=1
max=1000
