#KNOWN ISSUES & LIMITATIONS
#if items being bought back from shop reach 4 or less, the script will miss the click and waste the remaining material
#if items being sold to shop run out, the first item slot will disappear causing the second slot to be in the wrong place.

#DO NOT SELL ALL ITEMS FROM INVENTORY, LEAVE AT LEAST 1 OF EACH MATERIAL!!
#DO NOT SELL ALL ITEMS FROM INVENTORY, LEAVE AT LEAST 1 OF EACH MATERIAL!!

#FOR EVERY RUN/LOOP, 150 MATERIAL WILL BE SOLD AND TURNED INTO 75 BINDING CONTRACTS
#FOR EVERY RUN/LOOP, 150 MATERIAL WILL BE SOLD AND TURNED INTO 75 BINDING CONTRACTS
#FOR EVERY RUN/LOOP, 150 MATERIAL WILL BE SOLD AND TURNED INTO 75 BINDING CONTRACTS
#FOR EVERY RUN/LOOP, 150 MATERIAL WILL BE SOLD AND TURNED INTO 75 BINDING CONTRACTS

[Sleep Brief]
min=450
max=1250

[Sleep Normal]
min=1800
max=4000

[Sleep Short]
min=900
max=2400

[Sleep Infuse]
min=4600
max=5600

[Magestix]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Buy Tab]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Sell Tab]
type=coordinate
xmin=
xmax=
ymin=
ymax=

#obelisk is clicked with Magestix's store open, make sure your interface is not blocking the Obelisk
[Obelisk]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Hellfire Metal - Buy]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Hellfire Metal - Sell]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Blood of Orcus - Buy]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Blood of Orcus - Sell]
type=coordinate
xmin=
xmax=
ymin=
ymax=

#DO NOT TOUCH, unless the right-click to buy option is clicking wrong. (setup on a 1920x1080 monitor)
#to fix, only adjust miny/maxy
[Offset - Buy]
minx=-65
maxx=65
miny=68
maxy=80

#DO NOT TOUCH, unless the right-click to sell option is clicking wrong. (setup on a 1920x1080 monitor)
#to fix, only adjust miny/maxy
[Offset - Sell]
minx=-65
maxx=65
miny=83
maxy=95
