#place the high/low alch icon(from spellbook) to be made in the corresponding skillbar position

[Skillbar Hotkey]
type=hotkey
hotkey=

[Sleep Brief]
min=450
max=1250

[Sleep Normal]
min=750
max=1500

[Sleep Short]
min=1000
max=3500

[Sleep Alch]
min=3500
max=5500

#coordinates for item to be alched in your inventory/backpack
[Item]
type=coordinate
xmin=
xmax=
ymin=
ymax=
