###ALT1 IS REQUIRED FOR THIS SCRIPT TO WORK
###ALT1 IS REQUIRED FOR THIS SCRIPT TO WORK
###ALT1 IS REQUIRED FOR THIS SCRIPT TO WORK

##setup AfkWarden to detect xp for Woodcutting, 36-40 seconds works well
##setup AfkWarden to detect xp for Woodcutting, 36-40 seconds works well
##setup AfkWarden to detect xp for Woodcutting, 36-40 seconds works well

#THIS SCRIPT STARTS WITH YOUR CHARACTER STANDING NEXT TO THE WEST TREE
#THIS SCRIPT STARTS WITH YOUR CHARACTER STANDING NEXT TO THE WEST TREE
#THIS SCRIPT STARTS WITH YOUR CHARACTER STANDING NEXT TO THE WEST TREE

#the script will first click when it detects AFKwarden has turned red, then it clicks the East Tree
#the script will first click when it detects AFKwarden has turned red, then it clicks the East Tree

#this is the coordinate where you right-click when setting up the script through its interface
#right-click the bar on AfkWarden that turns red when no xp gains are detected
[Pixel Coordinate]
type=coordinate
x=
y=

#timer is triggered once "red" pixel is detected
[Sleep Timer]
min=1
max=7500

#red pixel when AfkWarden stops detecting xp gains
[Red]
type=color
red=0x5D1616

#stand next to the West Tree when selecting/setting these coordinates
[East Tree]
type=coordinate
xmin=
xmax=
ymin=
ymax=

#stand next to the East Tree when selecting/setting these coordinates
[West Tree]
type=coordinate
xmin=
xmax=
ymin=
ymax=
