#using f1-f8 works well, f9 has conflicts with LLARS default hotkeys, these hotkeys can be changed in the "llars config.ini" file
#https://www.autohotkey.com/docs/v2/KeyList.htm
[Bank Preset]
type=hotkey
hotkey=

#timers are based on ms(1000ms = 1sec)
[Sleep Brief]
min=500
max=2250

[Sleep Normal]
min=1800
max=4800

[Sleep Short]
min=1000
max=4000

[Bank]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Crafter]
type=coordinate
xmin=
xmax=
ymin=
ymax=

#if option=false then portables will not renew
#portables should equal the amount of portables you want to renew
#IMPORTANT: Place 1 crafter down before starting script(if option=true)
#bank hotkey needs to match the bank preset you have the portable crafter placed in
#toolbar hotkey needs to match the toolbar slot the portable crafter is placed in to renew
[Renew]
option=
portables=
bank hotkey=
toolbar hotkey=
