#using f1-f8 works well, f9 has conflicts with LLARS default hotkeys, these hotkeys can be changed in the "llars config.ini" file
#https://www.autohotkey.com/docs/v2/KeyList.htm
[Bank Preset]
type=hotkey
hotkey=

#shortest of timers
#timers are based on ms(1000ms = 1sec)
[Sleep Brief]
min=450
max=1250

#longer/general timer
#timers are based on ms(1000ms = 1sec)
[Sleep Normal]
min=1800
max=4500

#medium length timer
#timers are based on ms(1000ms = 1sec)
[Sleep Short]
min=1000
max=3500

#timers are based on ms(1000ms = 1sec)
[Sleep Craft]
min=10000
max=15000

#use a North/South bank
#good banks to use: Al Kharid, Varrock East, Edgeville, Falador East&West, Well of Goodwill
[Bank Coords]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Amulet]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Ball of Wool]
type=coordinate
xmin=
xmax=
ymin=
ymax=
