[Item Config]
item=

#using f1-f8 works well, f9 has conflicts with LLARS default hotkeys, these hotkeys can be changed in the "llars config.ini" file
#https://www.autohotkey.com/docs/v2/KeyList.htm
[Bank Preset]
type=hotkey
hotkey=

#timers are based on ms(1000ms = 1sec)
[Sleep Brief]
min=450
max=1250

[Sleep Normal]
min=1800
max=4500

#timers are based on ms(1000ms = 1sec)
[Sleep Short]
min=1000
max=3500

#timers are based on ms(1000ms = 1sec)
[Sleep Craft]
min=27000
max=32000

[Bank]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Crafter]
type=coordinate
xmin=
xmax=
ymin=
ymax=

#if option=false then portables will not renew
#portables should equal the amount of portables you want to renew
#IMPORTANT: Place 1 crafter down before starting script(if option=true)
#bank hotkey needs to match the bank preset you have the portable crafter placed in
#toolbar hotkey needs to match the toolbar slot the portable crafter is placed in to renew
[Renew]
option=false
portables=
bank hotkey=
toolbar hotkey=

[Leather Gloves]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Leather Boots]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Leather Cowl]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Leather Vambraces]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Leather Body]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Leather Chaps]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Leather Shield]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Hard Leather Gloves]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Hard Leather Boots]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Hard Leather Cowl]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Hard Leather Body]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Hard Leather Chaps]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Hard Leather Shield]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Studded Leather Gloves]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Studded Leather Boots]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Studded Leather Coif]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Studded Body]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Studded Chaps]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Studded Leather Shield]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Imphide Gloves]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Imphide Boots]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Imphide Hood]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Imphide Robe Bottom]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Imphide Robe Top]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Imphide Book]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Imphorn Wand]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Imphide Shield]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Carapace gloves]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Carapace boots]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Carapace helm]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Carapace legs]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Carapace torso]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Carapace shield]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Snakeskin boots]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Snakeskin vambraces]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Snakeskin bandana]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Snakeskin chaps]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Snakeskin body]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Green dragonhide vambraces]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Green dragonhide boots]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Green dragonhide chaps]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Green dragonhide coif]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Green dragonhide body]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Green dragonhide shield]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Blue dragonhide vambraces]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Blue dragonhide boots]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Blue dragonhide chaps]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Blue dragonhide coif]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Blue dragonhide body]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Blue dragonhide shield]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Wizard gloves]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Black wizard gloves]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Wizard boots]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Black wizard boots]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Wizard hat]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Black wizard hat]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Wizard robe skirt]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Black wizard robe skirt]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Wizard robe top]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Black wizard robe top]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Wizard book]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Wizard wand]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Wizard shield]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Black wizard shield]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Spider silk gloves]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Spider silk boots]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Spider silk hood]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Spider silk robe bottom]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Spider silk robe top]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Spider orb]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Spider wand]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Spider silk shield]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Batwing gloves]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Batwing boots]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Batwing hood]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Batwing legs]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Batwing torso]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Batwing book]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Batwing wand]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Batwing shield]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Mystic gloves]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Mystic boots]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Mystic hat]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Mystic robe bottom]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Mystic robe top]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Mystic orb]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Mystic wand]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Mystic shield]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Yak-hide legs]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Yak-hide body]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Fremennik round shield]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Cryptbloom gloves]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Cryptbloom boots]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Cryptbloom helm]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Cryptbloom bottoms]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Cryptbloom top]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Red dragonhide vambraces]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Red dragonhide boots]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Red dragonhide chaps]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Red dragonhide coif]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Red dragonhide body]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Red dragonhide shield]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Black dragonhide vambraces]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Black dragonhide boots]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Black dragonhide chaps]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Black dragonhide coif]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Black dragonhide body]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Black dragonhide shield]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Royal dragonhide vambraces]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Royal dragonhide boots]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Royal dragonhide chaps]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Royal dragonhide coif]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Royal dragonhide body]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Fungal visor]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Fungal leggings]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Fungal poncho]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Grifolic visor]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Grifolic leggings]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Grifolic poncho]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Ganodermic visor]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Ganodermic leggings]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Ganodermic poncho]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Death Lotus hood]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Death Lotus chestplate]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Death Lotus chaps]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Superior Death Lotus hood]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Superior Death Lotus chestplate]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Superior Death Lotus chaps]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Superior Death Lotus tabi]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Superior Death Lotus teko]
type=coordinate
xmin=
xmax=
ymin=
ymax=
