#AGGRESSION POT/FLASK IS NEEDED FOR THIS TO WORK LONGER THAN 10 MINUTES
#AGGRESSION POT/FLASK IS NEEDED FOR THIS TO WORK LONGER THAN 10 MINUTES
#AGGRESSION POT/FLASK IS NEEDED FOR THIS TO WORK LONGER THAN 10 MINUTES

#MAKE SURE TO SET HOTKEY FOR [AGRO]
#ALL OTHER SECTIONS ARE OPTIONAL

#MAKE SURE TO SET HOTKEY FOR [AGRO]
#ALL OTHER SECTIONS ARE OPTIONAL

#used for logging out if enabled in LLARS Config
#timers are based on ms(1000ms = 1sec)
[Sleep Short]
min=1000
max=3500

[Sleep Brief]
min=600
max=1800

#timer for aggression pot/flask
#timers are based on ms(1000ms = 1sec)
#place your agro pot/flask in your hotbar and set the hotkey to match
[Agro]
type=hotkey
option=true
hotkey=
min=330000
max=357000

#timer for prayer renew flask
#timers are based on ms(1000ms = 1sec)
#place your prayer pot/flask in your hotbar and set the hotkey to match
[Prayer]
type=hotkey
option=false
hotkey=
min=330000
max=355000

#no need to touch unless changing min/max
#timer for anti-afk
#timers are based on ms(1000ms = 1sec)
[AFK]
option=true
min=840000
max=894000

#strength pot/flask
#place your strength pot/flask in your hotbar and set the hotkey to match
#timers are based on ms(1000ms = 1sec)
[Strength]
type=hotkey
option=false
hotkey=
min=
max=

#attack pot/flask
#place your attack pot/flask in your hotbar and set the hotkey to match
#timers are based on ms(1000ms = 1sec)
[Attack]
type=hotkey
option=false
hotkey=
min=
max=

#magic pot/flask
#place your magic pot/flask in your hotbar and set the hotkey to match
#timers are based on ms(1000ms = 1sec)
[Magic]
type=hotkey
option=false
hotkey=
min=
max=

#ranged pot/flask
#place your ranged pot/flask in your hotbar and set the hotkey to match
#timers are based on ms(1000ms = 1sec)
[Ranged]
type=hotkey
option=false
hotkey=
min=
max=

#overload pot/flask
#place your overload pot/flask in your hotbar and set the hotkey to match
#timers are based on ms(1000ms = 1sec)
[Overload]
type=hotkey
option=false
hotkey=
min=
max=

#warmaster flask
#place your warmaster pot/flask in your hotbar and set the hotkey to match
#timers are based on ms(1000ms = 1sec)
[Warmaster]
type=hotkey
option=false
hotkey=
min=
max=

#antifire pot/flask
#place your antifire pot/flask in your hotbar and set the hotkey to match
#timers are based on ms(1000ms = 1sec)
[Antifire]
type=hotkey
option=false
hotkey=
min=
max=

#antipoison pot/flask
#place your antipoison pot/flask in your hotbar and set the hotkey to match
#timers are based on ms(1000ms = 1sec)
[Antipoison]
type=hotkey
option=false
hotkey=
min=
max=

#weapon poison pot/flask
#timers min&max set to normal weapon posion, not +, ++, or +++
#adjust min&max to fit your tier of poison
#place your weapon poison pot/flask in your hotbar and set the hotkey to match
#timers are based on ms(1000ms = 1sec)
[Weapon Poison]
type=hotkey
option=false
hotkey=
min=129000
max=144000

#Animate Dead Ancient Magicks spell
[Animate Dead]
type=hotkey
option=false
hotkey=
min=690000
max=711000

[Vecna Skull]
type=hotkey
option=false
hotkey=
min=420000
max=425000

[Ancient Elven Ritual Shard]
type=hotkey
option=false
hotkey=
min=303000
max=308000

[Incense Sticks]
type=hotkey
option=false
hotkey=
min=585000
max=595000

#Defence, Protection, Item protection, Pulverising, Burials, Penance
[Prayer Powder]
type=hotkey
option=false
hotkey=
min=1791000
max=1797000

#Timer is set for Bunyip
[Summon]
type=hotkey
option=false
hotkey=
min=2595000
max=2625000

#no default timer since that is highly subjective per user
[Saradomin Brew]
type=hotkey
option=false
hotkey=
min=
max=

#this option if set to true, will randomly press {space} between 15-60 second (default) to pick-up items on ground
#this option is helpful for picking up items that stack, charms, and bones/ash if you have the Necromancy book from City of Um easy tasks
[Loot]
option=false
min=10000
max=45000

#used for clicking the cannon to restock
[Cannon Restock]
type=coordinate
option=false
min=10000
max=30000
xmin=
xmax=
ymin=
ymax=

#used for noting binding contracts during combat
[Binding Contract]
option=false
min=10000
max=30000

#magic/enchanted notepaper inventory slot coordinates
[Notepaper - Binding Contract]
type=coordinate
depends=Binding Contract
xmin=
xmax=
ymin=
ymax=

#contract inventory slot coordinates
[Contract - Binding Contract]
type=coordinate
depends=Binding Contract
xmin=
xmax=
ymin=
ymax=
