#Each independent timer can have its own enabled state and random range.
#Duplicate/rename these sections as needed.

[Timer One]
option=false
min=10000
max=30000

[Timer Two]
option=false
min=30000
max=60000
