#Add script-specific configuration sections below.
#Examples:

[Example Coordinate]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Example Hotkey]
type=hotkey
hotkey=

[Sleep Short]
min=500
max=1000
