#Pixel to monitor.
[Pixel Coordinate]
type=coordinate
x=
y=

#Color that triggers the script action.
[Target Color]
type=color
color=0xFFFFFF

#Example action area after the color is detected.
[Action Location]
type=coordinate
xmin=
xmax=
ymin=
ymax=

#Example randomized delay before the action.
[Sleep Timer]
min=1
max=1000
