#can also make arrows, change to "item=arrow shaft"
[Bow Type]
item=

#using f1-f8 works well, f9 has conflicts with LLARS default hotkeys, these hotkeys can be changed in the "llars config.ini" file
#https://www.autohotkey.com/docs/v2/KeyList.htm
[Bank Preset]
type=hotkey
hotkey=

#timers are based on ms(1000ms = 1sec)
[Sleep Brief]
min=450
max=1250

[Sleep Normal]
min=1800
max=4500

[Sleep Short]
min=1000
max=3500

[Sleep Fletch]
min=18000
max=23000

[Bank]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Fletcher]
type=coordinate
xmin=
xmax=
ymin=
ymax=

#if option=false then portables will not renew
#portables should equal the amount of portables you want to renew
#IMPORTANT: Place 1 crafter down before starting script(if option=true)
#bank hotkey needs to match the bank preset you have the portable crafter placed in
#toolbar hotkey needs to match the toolbar slot the portable crafter is placed in to renew
[Renew]
option=
portables=
bank hotkey=
toolbar hotkey=

#always in the same spot regardless of log type
[Arrow shaft]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Shortbow]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Shieldbow]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Oak shortbow]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Oak shieldbow]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Willow shortbow]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Willow shieldbow]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Maple shortbow]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Maple shieldbow]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Yew shortbow]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Yew shieldbow]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Magic shortbow]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Magic shieldbow]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Wooden Stock]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Oak Stock]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Willow Stock]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Teak Stock]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Maple Stock]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Mahogany Stock]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Yew Stock]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Blisterwood Stock]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Magic Stock]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Unstrung Comp Bow]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Teak Stock]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Mahogany stock]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Elder arrow shaft]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Elder shortbow]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Elder shieldbow]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Blisterwood orb]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Blisterwood polearm]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Blisterwood sickle]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Blisterwood staff]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Blisterwood stake-thrower crossbow]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Blisterwood stock]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Blisterwood wand]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Off-hand blisterwood sickle]
type=coordinate
xmin=
xmax=
ymin=
ymax=

[Off-hand blisterwood stake]
type=coordinate
xmin=
xmax=
ymin=
ymax=
